// Public API facade. Existing imports remain compatible.
export { default, API_BASE_URL } from './api/client'
export { authApi } from './api/authApi'
export { emailApi } from './api/emailApi'
export { emailAccountsApi } from './api/emailAccountsApi'
export { aiApi } from './api/aiApi'
export { promptApi } from './api/promptApi'
export { agentApi } from './api/agentApi'
export { draftApi } from './api/draftApi'
export { autoReplyApi } from './api/autoReplyApi'
export { briefingsApi } from './api/briefingsApi'
export { followupsApi } from './api/followupsApi'
export { hostedEmailApi } from './api/hostedEmailApi'
export { sharedInboxApi } from './api/sharedInboxApi'
export { deliverabilityApi } from './api/deliverabilityApi'
export { executiveApi } from './api/executiveApi'
export { insightsApi } from './api/insightsApi'
export { workflowsApi } from './api/workflowsApi'
export { agentsApi } from './api/agentsApi'
export { campaignsApi } from './api/campaignsApi'
export { analyticsApi } from './api/analyticsApi'
export { healthApi } from './api/healthApi'
export { testConnection } from './api/testConnection'
export { tokenUtils } from './api/tokenUtils'
export { createWebSocket } from './api/createWebSocket'
export { monitorConnection } from './api/monitorConnection'
